### ISSUE TITLE
$sceDelegateProvider wrong parameters

### ISSUE THREAD

**Issue by SamuelBourdon** [chandermani/angularjsbyexample#2]
After struggling for a moment with $sceDelegateProvider error, i managed to get ride of it changing the url format for youtube :

```
    $sceDelegateProvider.resourceUrlWhitelist([
      // Allow same origin resource loads.
      'self',
      // Allow loading from our assets domain.  Notice the difference between * and **.
      '*://www.youtube.com/**'
    ]);
```

**Comment by chandermani** [comment]
Let me check and get back to you. What was the error you were getting?

**Comment by SamuelBourdon** [comment]
Sorry it works now using  `'http://*.youtube.com/**'` too
Maybe it was just a local problem

( I'm at chapter 4)
